name: disable workflow

on:
 push:
  branches: [ main ]

jobs:
  disable:
    runs-on: ubuntu-latest

    steps:
      - name: Disable workflow
        run: echo "Hello The Disable workflow is done by me"





